// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: InstantCommand.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.AlgaeGrabber;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class ChangeAlgaeArmLevel extends InstantCommand {

    private final AlgaeGrabber m_algaeGrabber;
    private int m_algaeArmLevel;

    public ChangeAlgaeArmLevel(int algaeArmLevel, AlgaeGrabber subsystem) {
        m_algaeArmLevel = algaeArmLevel;

        m_algaeGrabber = subsystem;
        addRequirements(m_algaeGrabber);
    }

    @Override
    public void execute() {
        m_algaeGrabber.goToSetpoint(m_algaeArmLevel);
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
